# **Практическое занятие 6: знакомимся с `numpy`**

## **План занятия**

- Обсуждение плана занятия
- Повторение лекции
- Самостоятельная работа + вопросы

# Модуль `numpy`

Перед работой с `numpy` его всегда необходимо импортировать:

In [6]:
import numpy as np

Основу `numpy` составляют `ndarray` &ndash; класс (тип) данных, в котором можно удобно хранить многомерные массивы данных. Их можно создать несколькими разными способами. Самый простой &ndash; из списка:

In [2]:
example = np.array([1, 2, 3, 4, 5, 6])
print(example, type(example))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


Другие способы создать массив (шаблоны):

In [3]:
print('Нолики: ')
print(np.zeros([3, 3])) # в качестве аргумента указываем СПИСОК с размером
                        # np.zeros(3, 3) не сработает!

print('ones:')
print(np.ones([3, 3]))

print('Arange с началом (1), концом (10) и шагом (0.1):')
print(np.arange(1, 10, 0.1))

Нолики: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange с началом (1), концом (10) и шагом (0.1):
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


`np.linspace` позволяет создавать массивы фиксированной длины (с равным промежутком между числами). Очень полезная функция:

In [7]:
print(np.linspace(0, np.pi, 100))

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

### Поэлементное умножение

- Если мы умножаем число на `ndarray`, то умножается весь массив. То же самое работает для всех других математических операций
- Если мы умножаем друг на друга `ndarray` **одинаковой длины**, то умножается каждый элемент одного массива на каждый элемент другого массива. Это же касается других математических операций.

Примеры:

In [5]:
a = np.arange(1, 10)
print('Умножаем массив на число:')
print(f'Массив a = {a}')
print(f'Массив a * 2 = {a*2}\n')

b = np.arange(1, 10)
print(f'Массив b = {b}')
print(f'Результат умножения a * b = {a*b}\n')

print(f'Результат сложения a + b = {a+b}\n')

print(f'Результат деления a/b = {a/b}')

Умножаем массив на число:
Массив a = [1 2 3 4 5 6 7 8 9]
Массив a * 2 = [ 2  4  6  8 10 12 14 16 18]

Массив b = [1 2 3 4 5 6 7 8 9]
Результат умножения a * b = [ 1  4  9 16 25 36 49 64 81]

Результат сложения a + b = [ 2  4  6  8 10 12 14 16 18]

Результат деления a/b = [1. 1. 1. 1. 1. 1. 1. 1. 1.]


Не получится перемножить массивы разной длины друг на друга:

In [8]:
array_len_10 = np.arange(10)
array_len_5 = np.arange(5)
array_len_10*array_len_5

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

Мы можем узнать информацию о массивах с помощью следующих комманд:

In [9]:
print(f'Размер массива аrray_len_10 = {array_len_10.shape}') # размер массива
print(f'Длина массива аrray_len_10 = {len(array_len_10)}\n') # работает и функция len!

zeros = np.zeros([3, 3])
print(f'Матрица zeros: \n{zeros}')
print(f'Размер матрицы zeros = {zeros.shape}')

print(f'Количество измерений матрицы zeros = {zeros.ndim}') # то же самое что len(zeros.shape)

Размер массива аrray_len_10 = (10,)
Длина массива аrray_len_10 = 10

Матрица zeros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Размер матрицы zeros = (3, 3)
Количество измерений матрицы zeros = 2


## Базовое индексирование массивов `numpy`

Посмотрим на базовые примеры работы с матрицами и векторами. Индексирование вектора (одномерного массива) очень похоже на индексирование списков. А вот индексирование матриц немного отличается.

Синтаксис:
- `A[i, j]` - элемент в `i`-ой строчке и в `j`-ом столбце.
- `A[0, 0]` - элемент на строчке `0` и столбце `0`
- `A[:, 0]` - нулевой столбец
- `A[0, :]` - нулевая строчка

In [12]:
A = np.array([[1, 1, 1],
              [2, 2, 30],
              [3, 3 ,3]])

print(f'A[0, 0] = {A[0, 0]}')
print(f'Нулевой столбец: A[:, 0] = {A[:, 0]}')
print(f'Нулевая строчка: A[0, :] = {A[0, :]}')

A[0, 0] = 1
Нулевой столбец: A[:, 0] = [1 2 3]
Нулевая строчка: A[0, :] = [1 1 1]


# Семинарские задания и домашние задания (0.8 баллов)

## Здравствуйте почему у меня ошибка в коде

**(0.05 балла)** Почему может быть ошибка в следующей ячейке?

In [14]:
import numpy as np
print(numpy.zeros(10))

NameError: name 'numpy' is not defined

**(0.075 балла)** А в этой?

In [12]:
example = np.array([1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

**(0.075 балла)** А с этой что не так?

In [15]:
print(np.zeros(3, 3))

TypeError: Cannot interpret '3' as a data type

**(0.05 балла)** А тут-то чего не так....

In [16]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3 ,3]])
print(A.shape())

TypeError: 'tuple' object is not callable

**(0.075 балла)** Да хватит уже блин когда это уже закончится помогите (найдите ошибку)


In [18]:
lat = np.arange(20, 40, 0.1)
lon = np.arange(-30, 30, 0.2)

print(np.sqrt(lat**2 + lon**2)) 

ValueError: operands could not be broadcast together with shapes (200,) (300,) 

### Ура данные

Выполните строчку ниже:

In [25]:
temps = np.loadtxt('data/temps.txt')

Это датасет, который я давал как один из примеров работы с проектами. Я немного обрезал его так, чтобы он удобно читался.

Он состоит из нескольких столбцов, разделенных пробелами. После считывания ее функцией `np.loadtxt` получаем матрицу размера `2089 x 12`:

In [21]:
temps.shape

(2089, 12)

(**0.075 балла**) Сделайте новые переменные `year` и `month`, которые будут равные нулевому и первому столбцу данных соотвественно.

In [22]:
# Ваш код

(**0.075 балла**) Мы могли бы запись дату вот так:


`time = year + month/12`

Таким образом, март 1871 будет `1871 + 3/12 = 1871.25`. Сделайте новую переменную `t` из двух столбцов `year` и `month`. `t.shape` должен быть равен `(2089,)` или `(2089, 1)`.

In [31]:
# Ваш код

### Ну это рандом

**(0.1 балла)** Используя функцию `np.random.randn(100)` (число в скобках означает количество элементов в массиве) создайте массив из 100 случайных чисел и найдите среднее значение, минимальное и максимальное число в массиве. Вам пригодится гугл и [документация `numpy`](https://numpy.org/doc/1.26/reference/index.html#reference)

In [2]:
# Ваш код

### ✨ Ну кто там у тебя краш

**(0.075 балла)** Сделайте вектор из 100 значений от `0` до `5`:

In [ ]:
# Ваш код

**(0.1 балла)**  Попробуйте посчитать вашу любимую функцию (если у вас нет любимой функции, то ~~пересмотрите ваши взгляды на жизнь~~ посчитайте, например, $y = \sqrt{x}$):

In [3]:
# Ваш код

### ✨ Нормально все? 

**(0.15 балла)** Используя:
```python
mu = 0
sigma = 1
```
и функцию `np.exp(x)` (это означает $e^{x}$) запишите формулу при `x` от `-5` до `5`:
$$\Large \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$$

Эта функция называется [функцией Гаусса](https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D1%83%D1%81%D1%81%D0%BE%D0%B2%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F), mu &mdash; среднее значение этой функции, а sigma &mdash; стандартное отклонение. 

In [ ]:
# Ваш код

✨ **(0.15 балла)** Используя [формулу оценки дисперсии случайной величины](https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D1%81%D0%BF%D0%B5%D1%80%D1%81%D0%B8%D1%8F_%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B9%D0%BD%D0%BE%D0%B9_%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B8%D0%BD%D1%8B): 
$$S = 1/n\sum(X - mean(X))^2$$
где `mean` &mdash; среднее массива, `n` &mdash; количество элементов в массиве, `X` &mdash; массив случайных чисел, найдите дисперсию полученного массива.


In [ ]:
# Ваш код

###  ✨ Память поколений

**(0.2 балла)** Придумайте задачку для домашнего задания или семинара для следующих поколений студентов ФГГТ!

- Задачи должны быть оригинальными или существенно видоизмененными (и точно не должны гуглиться)
- Языковые модели использовать нельзя
- Хихи-хаха поощряются, но все хорошо в меру
- В задачке должна быть указано для какой она недели (от первой до пятой)
- Задачка должна быть на тему лекции, в ней не должны использоваться констукции `python` вне курса или из следующих лекций
- Задачка должна прилагаться с решением

In [ ]:
# Ваша задачка

### ✨ Триангулируем портал в энд

В компьютерной игре `minecraft` используется весьма оригинальный способ нахождения портала в измерение края (`End dimension`): игрок должен запустить [око края](https://ru.minecraft.wiki/w/%D0%9E%D0%BA%D0%BE_%D0%9A%D1%80%D0%B0%D1%8F), оно полетит вверх и в сторону портала и немного зависнет в воздухе. Игрок должен запомнить куда оно полетело, и двигаться в сторону портала запуская `ока края` до тех пор, пока они не изменят своего направления, показывая уже вниз.

Впрочем, известно, что можно найти портал и более хитрым способом: запустить два `ока края` находясь на некотором удалении друг от друга. Зная точные координаты запуска и угол полета ока с помощью [экрана отладки](https://ru.minecraft.wiki/w/%D0%AD%D0%BA%D1%80%D0%B0%D0%BD_%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8) можно получить точные координаты с помощью теоремы косинусов. Более подробно с формулами в [этом видео](https://www.youtube.com/watch?v=hAKY7XyZqOo). Такой процесс называется триангуляцией и может часто использоваться физике/географии.

**(0.2 балла)** Помогите легендарному игроку `popbob`-у найти портал в измерение края. Находясь в координатах `(0, 0)` (x, z) он запустил око края и получил угол в `109.9` градусов, отошел в координаты `(-350, 0)`, запустил еще одно око края и получил угол в `115` градусов (координаты как в видео выше). Помогите ему найти точные координаты портала!

In [ ]:
# Ваш код

**(0.1 балла)** Напишите и **(0.1 балла)** продокументируйте функцию для поиска портала.

In [ ]:
# Ваш код

### Infamous griefer popbob
✨✨✨ **(Без балла)** В давние времена, легендарный игрок `popbob` на старейшем анархо-сервере в майнкрафте `2b2t` [триангулировал местоположение игроков по звуку грома](https://www.youtube.com/watch?v=T2H527m60bQ). Однако навестись на звук грома гораздо сложнее, чем на местоположение ока края, поэтому представим, что у нас есть погрешность в `+- 5 градусов`. Помогите ему найти точки, в которых могут находится игроки:

In [ ]:
# Ваш код

✨✨✨✨✨ **(Без балла)** Что будет, если описывать погрешность угла вероятностным нормальным распредлением с полушириной в `5 градусов`?

In [ ]:
# Ваш код

### Редкая гадость

✨✨✨ (**Без балла**) Реализуйте [метод Гаусса](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%93%D0%B0%D1%83%D1%81%D1%81%D0%B0) с помощью `numpy`. 

In [ ]:
# Ваш код